[package]
name = "test_utils"
description = "Postman collection runner and utility"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
license.workspace = true

[features]
default = ["dummy_connector", "payouts"]
dummy_connector = []
payouts = []

[dependencies]
async-trait = "0.1.68"
base64 = "0.21.2"
clap = { version = "4.3.2", default-features = false, features = ["std", "derive", "help", "usage"] }
rand = "0.8.5"
regex = "1.10.3"
reqwest = { version = "0.11.18", features = ["native-tls"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_urlencoded = "0.7.1"
serial_test = "2.0.0"
thirtyfour = "0.31.0"
time = { version = "0.3.21", features = ["macros"] }
tokio = "1.36.0"
toml = "0.7.4"

# First party crates
masking = { version = "0.1.0", path = "../masking" }
