[package]
name = "test_utils"
description = "Postman collection runner and utility"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
license.workspace = true

[features]
default = ["dummy_connector"]
dummy_connector = ["api_models/dummy_connector"]


[dependencies]
clap = { version = "4.3.2", default-features = false, features = ["derive"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_path_to_error = "0.1.11"
toml = "0.7.4"

# First party crates
router = { version = "0.2.0", path = "../router" }
api_models = { version = "0.1.0", path = "../api_models", features = ["errors"] }
masking = { version = "0.1.0", path = "../masking" }
