[package]
name = "test_utils"
description = "Postman collection runner and utility"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
license.workspace = true

[features]
default = ["dummy_connector", "payouts"]
dummy_connector = []
payouts = []

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
base64 = "0.22.1"
clap = { version = "4.5.38", default-features = false, features = ["std", "derive", "help", "usage"] }
rand = "0.8.5"
regex = "1.11.1"
reqwest = { version = "0.11.27", features = ["native-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_urlencoded = "0.7.1"
serial_test = "3.2.0"
thirtyfour = "0.31.0"
time = { version = "0.3.41", features = ["macros"] }
tokio = "1.48.0"
toml = "0.8.22"

# First party crates
masking = { version = "0.1.0", path = "../masking" }
common_enums = { version = "0.1.0", path = "../common_enums" }

[lints]
workspace = true
