[package]
name = "masking"
description = "Personal Identifiable Information protection. Wrapper types and traits for secret management which help ensure they aren't accidentally copied, logged, or otherwise exposed (as much as possible), and also ensure secrets are securely wiped from memory when dropped."
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
readme = "README.md"
license = "Apache-2.0"

[features]
default = ["alloc", "serde", "diesel"]
alloc = ["zeroize/alloc"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
subtle = "2.4.1"
bytes = { version = "1", optional = true }
diesel = { git = "https://github.com/juspay/diesel", features = ["postgres", "serde_json", "time"], optional = true, rev = "22f3f59f1db8a3f61623e4d6b375d64cd7bd3d02" }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = "1.0.89"
zeroize = { version = "1.5", default-features = false }

[dev-dependencies]
serde_json = "1.0.89"
