[package]
name = "scheduler"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["kv_store", "olap"]
olap = ["storage_impl/olap"]
kv_store = []
email = ["external_services/email"]

[dependencies]
# Third party crates
async-trait = "0.1.79"
error-stack = "0.4.1"
futures = "0.3.30"
num_cpus = "1.16.0"
once_cell = "1.19.0"
rand = "0.8.5"
serde = "1.0.197"
serde_json = "1.0.115"
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.58"
time = { version = "0.3.35", features = ["serde", "serde-well-known", "std"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.8.0", features = ["v4"] }

# First party crates
common_utils = { version = "0.1.0", path = "../common_utils", features = ["signals", "async_ext"] }
diesel_models = { version = "0.1.0", path = "../diesel_models", features = ["kv_store"] }
external_services = { version = "0.1.0", path = "../external_services" }
redis_interface = { version = "0.1.0", path = "../redis_interface" }
router_env = { version = "0.1.0", path = "../router_env", features = ["log_extra_implicit_fields", "log_custom_entries_to_extra"] }
storage_impl = { version = "0.1.0", path = "../storage_impl", default-features = false }

# [[bin]]
# name = "scheduler"
# path = "src/bin/scheduler.rs"
