[package]
name = "euclid"
description = "DSL for static routing"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
erased-serde = "0.3.28"
frunk = "0.4.1"
frunk_core = "0.4.1"
nom = { version = "7.1.3", features = ["alloc"], optional = true }
once_cell = "1.18.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.193", features = ["derive", "rc"] }
serde_json = "1.0.108"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0.43"
utoipa = { version = "3.3.0", features = ["preserve_order"] }

# First party dependencies
common_enums = { version = "0.1.0", path = "../common_enums" }
euclid_macros = { version = "0.1.0", path = "../euclid_macros" }

[features]
ast_parser = ["dep:nom"]
valued_jit = []
connector_choice_mca_id = []
dummy_connector = []

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "backends"
harness = false
required-features = ["ast_parser", "valued_jit"]
