apiVersion: 1

datasources:
  - name: Traces
    type: tempo
    access: proxy
    url: http://tempo:3200/
    editable: true
    isDefault: false
  - name: Logs
    type: loki
    access: proxy
    url: http://loki:3100/
    editable: true
    isDefault: true
  - name: Metrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090/
    editable: true
  - name: Profiling
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040/
    editable: true
    isDefault: false
    jsonData:
      minStep: '1s'
      queryType: 'both'
      groupByKey: ''
    datasources:
  # - name: ClickHouse
  #   type: grafana-clickhouse-datasource
  #   jsonData:
  #     defaultDatabase: default
  #     port: 9000
  #     server: clickhouse-server
  #     username: default
  #     tlsSkipVerify: true
  #     protocol: native
  #   editable: true