[package]
name = "openapi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# Third party crates
serde_json = "1.0.140"
utoipa = { version = "4.2.3", features = ["preserve_order", "preserve_path_order", "time"] }

# First party crates
api_models = { version = "0.1.0", path = "../api_models", features = ["frm", "payouts", "openapi", "errors"] }
common_utils = { version = "0.1.0", path = "../common_utils", features = ["logs"] }
common_types = { version = "0.1.0", path = "../common_types" }
router_env = { version = "0.1.0", path = "../router_env" }
euclid = { version = "0.1.0", path = "../euclid" }

[features]
v2 = ["api_models/v2", "common_utils/v2", "api_models/tokenization_v2"]
v1 = ["api_models/v1", "common_utils/v1"]

[lints]
workspace = true
