[package]
name = "router_env"
description = "Environment of payment router: logger, basic config, its environment awareness."
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
license.workspace = true

[dependencies]
cargo_metadata = "0.15.4"
config = { version = "0.13.3", features = ["toml"] }
error-stack = "0.3.1"
gethostname = "0.4.3"
once_cell = "1.18.0"
opentelemetry = { version = "0.19.0", features = ["rt-tokio-current-thread", "metrics"] }
opentelemetry-otlp = { version = "0.12.0", features = ["metrics"] }
rustc-hash = "1.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_path_to_error = "0.1.11"
strum = { version = "0.24.1", features = ["derive"] }
time = { version = "0.3.21", default-features = false, features = ["formatting"] }
tokio = { version = "1.28.2" }
tracing = { version = "=0.1.36" }
tracing-actix-web = { version = "0.7.8", features = ["opentelemetry_0_19", "uuid_v7"], optional = true }
tracing-appender = { version = "0.2.2" }
tracing-attributes = "=0.1.22"
tracing-opentelemetry = { version = "0.19.0" }
tracing-subscriber = { version = "0.3.17", default-features = true, features = ["env-filter", "json", "registry"] }
vergen = { version = "8.2.1", optional = true, features = ["cargo", "git", "git2", "rustc"] }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
cargo_metadata = "0.15.4"
vergen = { version = "8.2.1", features = ["cargo", "git", "git2", "rustc"], optional = true }

[features]
default = ["actix_web", "payouts"]
actix_web = ["tracing-actix-web"]
log_custom_entries_to_extra = []
log_extra_implicit_fields = []
log_active_span_json = []
payouts = []
