[package]
name = "router_env"
description = "Environment of payment router: logger, basic config, its environment awareness."
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
readme = "README.md"
license = "Apache-2.0"
build = "src/build.rs"

[dependencies]
config = { version = "0.13.2", features = ["toml"] }
gethostname = "0.2.3"
once_cell = "1.15.0"
opentelemetry = { version = "0.17", features = ["rt-tokio-current-thread", "metrics"] }
opentelemetry-otlp = { version = "0.10", features = ["metrics"] }
rustc-hash = "1.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
serde_urlencoded = "0.7.1"
strum = { version = "0.24.1", features = ["derive"] }
time = { version = "0.3.14", default-features = false, features = ["formatting"] }
tokio = { version = "1.21.2" }
tracing = "0.1.36"
tracing-actix-web = { version = "0.6.1", features = ["opentelemetry_0_17"], optional = true }
tracing-appender = "0.2.2"
tracing-core = "0.1.29"
tracing-opentelemetry = { version = "0.17" }
tracing-subscriber = { version = "0.3.15", default-features = true, features = ["json", "env-filter", "registry"] }

[dev-dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
vergen = { version = "7.4.2" }

[features]
default = ["actix_web"]
actix_web = ["tracing-actix-web"]
log_custom_entries_to_extra = []
log_extra_implicit_fields = []
