[package]
name = "router_env"
description = "Environment of payment router: logger, basic config, its environment awareness."
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
config = { version = "0.13.3", features = ["toml"] }
gethostname = "0.4.1"
once_cell = "1.17.1"
opentelemetry = { git = "https://github.com/open-telemetry/opentelemetry-rust/", rev = "44b90202fd744598db8b0ace5b8f0bad7ec45658", features = ["rt-tokio-current-thread", "metrics"] }
opentelemetry-otlp = { git = "https://github.com/open-telemetry/opentelemetry-rust/", rev = "44b90202fd744598db8b0ace5b8f0bad7ec45658", features = ["metrics"] }
rustc-hash = "1.1"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
serde_path_to_error = "0.1.10"
strum = { version = "0.24.1", features = ["derive"] }
time = { version = "0.3.20", default-features = false, features = ["formatting"] }
tokio = { version = "1.26.0" }
tracing = { version = "0.1.36" }
tracing-actix-web = { version = "0.7.2", features = ["opentelemetry_0_18"], optional = true }
tracing-appender = { version = "0.2.2" }
tracing-attributes = "=0.1.22"
tracing-opentelemetry = { version = "0.18.0" }
tracing-subscriber = { version = "0.3.16", default-features = true, features = ["env-filter", "json", "registry"] }
vergen = { version = "8.0.0-beta.9", optional = true, features = ["cargo", "git", "git2", "rustc"] }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
cargo_metadata = "0.15.4"
vergen = { version = "8.0.0-beta.9", features = ["cargo", "git", "git2", "rustc"], optional = true }

[features]
default = ["actix_web"]
actix_web = ["tracing-actix-web"]
log_custom_entries_to_extra = []
log_extra_implicit_fields = []
