name: Release SemVer tag

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build and push router Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            BINARY=router
          context: .
          push: true
          tags: juspaydotin/orca:${{ github.ref_name }}

      - name: Build and push consumer Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            BINARY=scheduler
            SCHEDULER_FLOW=consumer
          context: .
          push: true
          tags: juspaydotin/orca-consumer:${{ github.ref_name }}

      - name: Build and push producer Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            BINARY=scheduler
            SCHEDULER_FLOW=producer
          context: .
          push: true
          tags: juspaydotin/orca-producer:${{ github.ref_name }}

      - name: Build and push drainer Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            BINARY=drainer
          context: .
          push: true
          tags: juspaydotin/orca:drainer-${{ github.ref_name }}
